name:                photoPolysemy
version:             0.1.0.0
github:              "githubuser/photoPolysemy"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/photoPolysemy#readme>

dependencies:
- base-noprelude >= 4.12 && < 5
- lens >= 4.17 && < 4.18
- mtl >= 2.2 && < 2.3
- microlens-mtl >= 0.1 && < 0.2
- relude >= 0.4 && < 0.7
- aeson >= 1.4 && < 1.5
- conduit >= 1.3 && < 1.4
- conduit-extra >= 1.3 && < 1.4
- fsnotify >= 0.3 && < 0.4
- filepath >= 1.4 && < 1.5
- unordered-containers >= 0.2 && < 0.3
- threepenny-gui >= 0.8 && < 0.9
- cassava >= 0.5 && < 0.6
- vector >= 0.12 && < 0.13
- bytestring >= 0.10 && < 0.11
- directory >= 1.3 && < 1.4
- async >= 2.2 && < 2.3
- shake >= 0.18 && < 0.19
- time >= 1.8 && < 2.0
- ilist >= 0.3 && < 0.4
- strings >= 1.1 && < 1.2
- tasty >= 1.2 && < 1.3
- tasty-hspec >= 1.1 && < 1.2
- tasty-golden >= 2.3 && < 2.4
- extra >= 1.6 && < 1.7
- deepseq >= 1.4 && < 1.5
- strict-concurrency >= 0.2 && < 0.3


default-extensions:
- LambdaCase
- RecordWildCards
- OverloadedStrings
- DerivingStrategies
- DeriveGeneric
- DeriveFunctor

library:
  source-dirs: src

executables:
  photoPolysemy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - photoPolysemy

tests:
  photoPolysemy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - photoPolysemy
